In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# warning 없애기
import warnings
warnings.filterwarnings(action='ignore')
import platform
if platform.system() == 'Windows': # Windows
    plt.rc('font', family='Malgun Gothic')

# 데이터 불러오기

In [52]:
data = pd.read_csv('광고집행 모니터링 201901-202203.csv', encoding = 'cp949')
data

,업종,광고주,상품,연월,항목,지상파,라디오,신문,잡지,케이블(닐슨추정보너스),종편(닐슨추정보너스),디지털동영상,디지털배너,계
0,성인종합영양제,구주제약,구주알코덱스,19.10,금액,0,124405,0,0,0,0,0,0,124405
1,성인종합영양제,구주제약,구주알코덱스,19.10,횟수,0,498,0,0,0,0,0,0,498
2,성인종합영양제,구주제약,구주알코덱스,19.10,노출량,0,9960,0,0,0,0,0,0,9960
3,성인종합영양제,구주제약,구주알코덱스,19.11,금액,0,113545,0,0,0,0,0,0,113545
4,성인종합영양제,구주제약,구주알코덱스,19.11,횟수,0,437,0,0,0,0,0,0,437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,성인종합영양제,GC녹십자,GC녹십자비맥스액티브정,20.02,노출량,0,0,0,3,0,0,0,0,3
578,성인종합영양제,GC녹십자,GC녹십자비맥스액티브정,20.03,금액,0,0,0,4000,0,0,0,0,4000
579,성인종합영양제,GC녹십자,GC녹십자비맥스액티브정,20.03,횟수,0,0,0,2,0,0,0,0,2
580,성인종합영양제,GC녹십자,GC녹십자비맥스액티브정,20.03,노출량,0,0,0,2,0,0,0,0,2
581,성인종합영양제,GC녹십자,GC녹십자비맥스정,21.02,횟수,0,0,0,0,0,0,0,1,1

# 횟수 데이터 분리

In [4]:
data_count = data[data['항목']=='횟수']
data_count

,업종,광고주,상품,연월,항목,지상파,라디오,신문,잡지,케이블(닐슨추정보너스),종편(닐슨추정보너스),디지털동영상,디지털배너,계
1,성인종합영양제,구주제약,구주알코덱스,19.10,횟수,0,498,0,0,0,0,0,0,498
4,성인종합영양제,구주제약,구주알코덱스,19.11,횟수,0,437,0,0,0,0,0,0,437
7,성인종합영양제,구주제약,구주알코덱스,19.12,횟수,0,473,0,0,0,0,0,0,473
10,성인종합영양제,구주제약,구주알코덱스,20.01,횟수,0,420,0,0,0,0,0,0,420
13,성인종합영양제,구주제약,구주알코덱스,20.02,횟수,0,399,0,0,0,0,0,0,399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,성인종합영양제,GC녹십자,GC녹십자비맥스액티브정,19.12,횟수,0,0,0,1,0,0,0,0,1
573,성인종합영양제,GC녹십자,GC녹십자비맥스액티브정,20.01,횟수,0,0,0,2,0,0,0,0,2
576,성인종합영양제,GC녹십자,GC녹십자비맥스액티브정,20.02,횟수,0,0,0,3,0,0,0,0,3
579,성인종합영양제,GC녹십자,GC녹십자비맥스액티브정,20.03,횟수,0,0,0,2,0,0,0,0,2
581,성인종합영양제,GC녹십자,GC녹십자비맥스정,21.02,횟수,0,0,0,0,0,0,0,1,1

# 일동제약의 매체별 광고 횟수

In [103]:
#일동제약 라디오
ildong_radio = data_count[data_count['광고주']=='일동제약']['라디오'].sum()
#일동제약 신문
ildong_newspaper = data_count[data_count['광고주']=='일동제약']['신문'].sum()
#일동제약 TV 매체 Total
a = data_count[data_count['광고주']=='일동제약']['지상파'].sum()
b = data_count[data_count['광고주']=='일동제약']['케이블(닐슨추정보너스)'].sum()
c = data_count[data_count['광고주']=='일동제약']['종편(닐슨추정보너스)'].sum()
ildong_tv = a+b+c
#일동제약 잡지
ildong_magazine = data_count[data_count['광고주']=='일동제약']['잡지'].sum()
#일동제약 디지털동영상
ildong_digitalvideo = data_count[data_count['광고주']=='일동제약']['디지털동영상'].sum()
#일동제약 디지털배너
ildong_digitalbanner = data_count[data_count['광고주']=='일동제약']['디지털배너'].sum()

In [6]:
print(f'라디오 : {ildong_radio} \n신문 : {ildong_newspaper} \nTV : {ildong_tv} \n잡지 : {ildong_magazine} \n디지털동영상 : {ildong_digitalvideo} \n디지털배너 : {ildong_digitalbanner}')

라디오 : 0
신문 : 40
TV : 165602
잡지 : 2
디지털동영상 : 3272
디지털배너 : 27

# 일동제약의 월별 광고횟수(19.01~22.02)

In [106]:
data2 = data_count[data_count['광고주']=='일동제약']
data3 = data2.groupby(['연월']).sum().drop(['지상파','라디오','신문','잡지','케이블(닐슨추정보너스)','종편(닐슨추정보너스)','디지털동영상','디지털배너'], axis = 1)
data3 = data3.reset_index()
data3

       연월      계
0   19.01    131
1   19.02   6484
2   19.03  15207
3   19.04   6970
4   19.05   7903
5   19.06   7414
6   19.07    972
7   19.08   2372
8   19.09   9624
9   19.10   7983
10  19.11    534
11  19.12    101
12  20.01     26
13  20.02      3
14  20.03    886
15  20.04   6294
16  20.05   8307
17  20.06   6459
18  20.07   7482
19  20.08   4853
20  20.09   8578
21  20.10   7345
22  20.11    205
23  20.12    181
24  21.01    703
25  21.02   1295
26  21.03      1
27  21.04   6286
28  21.05  11325
29  21.06   7544
30  21.07   5927
31  21.08   3492
32  21.09   9350
33  21.10   2161
34  22.02   4545

# GC녹십자의 매체별 광고 횟수

In [42]:
#GC녹십자 라디오
gc_radio = data_count[data_count['광고주']=='GC녹십자']['라디오'].sum()
#GC녹십자 신문
gc_newspaper = data_count[data_count['광고주']=='GC녹십자']['신문'].sum()
#GC녹십자 TV 매체 Total
a = data_count[data_count['광고주']=='GC녹십자']['지상파'].sum()
b = data_count[data_count['광고주']=='GC녹십자']['케이블(닐슨추정보너스)'].sum()
c = data_count[data_count['광고주']=='GC녹십자']['종편(닐슨추정보너스)'].sum()
gc_tv = a+b+c
#GC녹십자 잡지
gc_magazine = data_count[data_count['광고주']=='GC녹십자']['잡지'].sum()
#GC녹십자 디지털동영상
gc_digitalvideo = data_count[data_count['광고주']=='GC녹십자']['디지털동영상'].sum()
#GC녹십자 디지털배너
gc_digitalbanner = data_count[data_count['광고주']=='GC녹십자']['디지털배너'].sum()

In [45]:
print(f'라디오 : {gc_radio} \n신문 : {gc_newspaper} \nTV : {gc_tv} \n잡지 : {gc_magazine} \n디지털동영상 : {gc_digitalvideo} \n디지털배너 : {gc_digitalbanner}')

라디오 : 0
신문 : 450
TV : 58067
잡지 : 90
디지털동영상 : 2088
디지털배너 : 3

# GC녹십자의 월별 광고횟수(19.01~22.02)

In [108]:
data4 = data_count[data_count['광고주']=='GC녹십자']
data5 = data4.groupby(['연월']).sum().drop(['지상파','라디오','신문','잡지','케이블(닐슨추정보너스)','종편(닐슨추정보너스)','디지털동영상','디지털배너'], axis = 1)
data6 = data5.reset_index()
data6

       연월     계
0   19.01    64
1   19.02     8
2   19.03     9
3   19.04    11
4   19.05    10
5   19.06    14
6   19.07    13
7   19.08    21
8   19.09     7
9   19.10    11
10  19.11    11
11  19.12    10
12  20.01   811
13  20.02  3103
14  20.03  1367
15  20.04     3
16  20.05   257
17  20.06  1608
18  20.07  1261
19  20.08  1151
20  20.09  1811
21  20.10   688
22  20.11   483
23  20.12    42
24  21.01  3291
25  21.02  7500
26  21.03  6625
27  21.04  6207
28  21.05  5116
29  21.06  3505
30  21.07  2817
31  21.08  1443
32  21.09  1503
33  21.10  3090
34  21.11  2553
35  21.12    16
36  22.01   640
37  22.02  3618